// <auto-generated />
using System;
using Lumel.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Lumel.Database.DeliveryAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("attemptDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("deliveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("driverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("monthValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("yearValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("deliveryLog");
                });
#pragma warning restore 612, 618
        }
    }
}
